// Change these
#macro		SPREAD_DEV_MODE							true
#macro		SPREAD_ALLOW_DEV_MODE_OUTSIDE_IDE		false
#macro		SPREAD_LOG_MESSAGE_LEVEL				SPREAD_MESSAGE_LEVEL.INFO
#macro		SPREAD_JSON_BUNDLE_PATHS				"json/"
#macro		SPREAD_JSON_BUNDLE_EXTENSION			".dat"
